#ifndef DEF_H
#define DEF_H

#define INT_BUF_SIZE 33
#define BASE_MEM_ADDRESS 100
#define WORD_LENGTH 16
#define EMPTY_WORD "000000000000000"
#define MEMORY_MAX 1000
#define LINE_MAX 80
#define SEGMENTS_MAX 3
#define I_COMMANDS_COUNTER 16
#define D_COMMANDS_COUNTER 4
#define COMMAND_MAX_LENGTH 8
#define OPERANDS_MAX 2
#define DATA_OPERANDS_MAX 37
#define REGISTERS_MAX 8

#define COMMENT_CHAR ';'
#define LABEL_CHAR ':'

#define DIRECT_OFFSET_START_CHAR '['
#define DIRECT_OFFSET_END_CHAR ']'
#define IMMIDIATE_CHAR '#'




#endif
